//Gastos
export const AGREGAR_GASTO_MAXI = 'AGREGAR_GASTO_MAXI';
export const AGREGAR_GASTO_GIGI = 'AGREGAR_GASTO_GIGI';
export const OBTENER_GASTO_MAXI = 'OBTENER_GASTO_MAXI';
export const OBTENER_GASTO_GIGI = 'OBTENER_GASTO_GIGI';
export const ELIMINAR_GASTOS_MAXI = 'ELIMINAR_GASTOS_MAXI';
export const ELIMINAR_GASTOS_GIGI = 'ELIMINAR_GASTOS_GIGI';
export const AGREGAR_MES = 'AGREGAR_MES';
export const AGREGAR_ANO = 'AGREGAR_ANO';
export const ELIMINAR_ALERTA = 'ELIMINAR_ALERTA';
export const ELIMINAR_TODOS_GASTOS_MAXI = 'ELIMINAR_TODOS_GASTOS_MAXI';
export const ELIMINAR_TODOS_GASTOS_GIGI = 'ELIMINAR_TODOS_GASTOS_GIGI';
export const AGREGAR_ALERTA = 'AGREGAR_ALERTA';

//Alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

//logeo
export const USUARIO_ACTUAL = 'USUARIO_ACTUAL';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';