//Gastos
export const AGREGAR_GASTO_MAXI = 'AGREGAR_GASTO_MAXI';
export const AGREGAR_GASTO_GIGI = 'AGREGAR_GASTO_GIGI';
export const OBTENER_GASTO_MAXI = 'OBTENER_GASTO_MAXI';
export const OBTENER_GASTO_GIGI = 'OBTENER_GASTO_GIGI';
export const ELIMINAR_GASTOS_MAXI = 'ELIMINAR_GASTOS_MAXI';
export const ELIMINAR_GASTOS_GIGI = 'ELIMINAR_GASTOS_GIGI';
export const AGREGAR_MES = 'AGREGAR_MES';
export const ELIMINAR_ALERTA = 'ELIMINAR_ALERTA';
export const ELIMINAR_TODOS_GASTOS_MAXI = 'ELIMINAR_TODOS_GASTOS_MAXI';
export const ELIMINAR_TODOS_GASTOS_GIGI = 'ELIMINAR_TODOS_GASTOS_GIGI';

//Alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

//logeo
export const USUARIO_ACTUAL = 'USUARIO_ACTUAL';