//Gastos
export const AGREGAR_GASTO_MAXI = 'AGREGAR_GASTO_MAXI';
export const AGREGAR_GASTO_GIGI = 'AGREGAR_GASTO_GIGI';
export const OBTENER_GASTO_MAXI = 'OBTENER_GASTO_MAXI';
export const OBTENER_GASTO_GIGI = 'OBTENER_GASTO_GIGI';
